version: "3.8"
services:
  notebook:
    image: music-to-scrape:latest
    command: jupyter notebook --port 9999 --NotebookApp.open_browser=False --NotebookApp.ip='0.0.0.0' --allow-root --NotebookApp.notebook_dir=/data
    environment:
      - USER=$USER
      - TZ=America/New_York
    ports:
      - 8080:80
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ~/data
        target: /data